// Skybot.FactoidViewer
// Skybot.FactoidViewer / FactoidsModelConfiguration.cs BY Kristian Schlikow
// First modified on 2023.03.15
// Last modified on 2023.03.15

namespace Skybot.FactoidViewer.Models

{
#region
    using Asp.Versioning;
    using Asp.Versioning.OData;

    using Microsoft.OData.ModelBuilder;
#endregion

    /// <summary>
    ///     Class FactoidsModelConfiguration.
    ///     Implements the <see cref="IModelConfiguration" />
    /// </summary>
    /// <seealso cref="IModelConfiguration" />
    /// <autogeneratedoc />
    public class FactoidsModelConfiguration : IModelConfiguration
    {
        /// <summary>
        ///     Applies model configurations using the provided builder for the specified API version.
        /// </summary>
        /// <param name="builder">
        ///     The <see cref="T:Microsoft.OData.ModelBuilder.ODataModelBuilder">builder</see> used to apply
        ///     configurations.
        /// </param>
        /// <param name="apiVersion">
        ///     The <see cref="T:Asp.Versioning.ApiVersion">API version</see> associated with the
        ///     <paramref name="builder" />.
        /// </param>
        /// <param name="routePrefix">The route prefix associated with the configuration, if any.</param>
        /// <autogeneratedoc />
        public void Apply(ODataModelBuilder builder, ApiVersion apiVersion, string? routePrefix)
        {
            switch (apiVersion.MajorVersion)
            {
            case 2:
                ConfigureV2(builder);

                break;

            default:
                ConfigureDefault(builder);

                break;
            }
        }

        /// <summary>
        ///     Configures the current.
        /// </summary>
        /// <param name="builder">The builder.</param>
        /// <returns>EntityTypeConfiguration&lt;Factoid&gt;.</returns>
        /// <autogeneratedoc />
        private static EntityTypeConfiguration<Factoid> ConfigureCurrent(ODataModelBuilder builder)
        {
            var factoid = builder.EntitySet<Factoid>("Factoid").EntityType;

            factoid.HasKey(e => e.Key);

            return factoid;
        }

        /// <summary>
        ///     Configures the v1.
        /// </summary>
        /// <param name="builder">The builder.</param>
        /// <autogeneratedoc />
        private static void ConfigureDefault(ODataModelBuilder builder)
        {
            var configure = ConfigureCurrent(builder);
            configure.Ignore(f => f.CreatedBy);
            configure.Ignore(f => f.ModifiedBy);
            configure.Ignore(f => f.LockedAt);
            configure.Ignore(f => f.LockedBy);
        }

        /// <summary>
        ///     Configures the v2.
        /// </summary>
        /// <param name="builder">The builder.</param>
        /// <autogeneratedoc />
        private static void ConfigureV2(ODataModelBuilder builder) => ConfigureCurrent(builder);
    }
}
