// Skybot.FactoidViewer
// Skybot.FactoidViewer / Factoid.cs BY Kristian Schlikow
// First modified on 2023.02.17
// Last modified on 2023.03.23

namespace Skybot.FactoidViewer.Models

{
#region
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
#endregion

    /// <summary>
    ///     Class Factoid.
    /// </summary>
    /// <autogeneratedoc />
    public class Factoid
    {
        /// <summary>
        ///     Gets or sets the key.
        /// </summary>
        /// <value>The key.</value>
        /// <autogeneratedoc />
        [Key]
        [Required]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public string Key { get; set; } = null!;

        /// <summary>
        ///     Gets or sets the created by.
        /// </summary>
        /// <value>The created by.</value>
        /// <autogeneratedoc />
        public string? CreatedBy { get; set; }

        /// <summary>
        ///     Gets or sets the created at.
        /// </summary>
        /// <value>The created at.</value>
        /// <autogeneratedoc />
        public long? CreatedAt { get; set; }

        /// <summary>
        ///     Gets or sets the modified by.
        /// </summary>
        /// <value>The modified by.</value>
        /// <autogeneratedoc />
        public string? ModifiedBy { get; set; }

        /// <summary>
        ///     Gets or sets the modified at.
        /// </summary>
        /// <value>The modified at.</value>
        /// <autogeneratedoc />
        public long? ModifiedAt { get; set; }

        /// <summary>
        ///     Gets or sets the locked at.
        /// </summary>
        /// <value>The locked at.</value>
        /// <autogeneratedoc />
        public long? LockedAt { get; set; }

        /// <summary>
        ///     Gets or sets the locked by.
        /// </summary>
        /// <value>The locked by.</value>
        /// <autogeneratedoc />
        public string? LockedBy { get; set; }

        /// <summary>
        ///     Gets or sets the fact.
        /// </summary>
        /// <value>The fact.</value>
        /// <autogeneratedoc />
        [Required]
        public string? Fact { get; set; }

        /// <summary>
        ///     Gets or sets the requested count.
        /// </summary>
        /// <value>The requested count.</value>
        /// <autogeneratedoc />
        public long? RequestedCount { get; set; }
    }
}
